# coding: utf-8

"""
    AM Portfolio API

    API for managing investment portfolios and market indices.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from am_portfolio_client.models.portfolio_analysis import PortfolioAnalysis

class TestPortfolioAnalysis(unittest.TestCase):
    """PortfolioAnalysis unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PortfolioAnalysis:
        """Test PortfolioAnalysis
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PortfolioAnalysis`
        """
        model = PortfolioAnalysis()
        if include_optional:
            return PortfolioAnalysis(
                portfolio_id = '',
                last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                current_interval = '1D'
            )
        else:
            return PortfolioAnalysis(
        )
        """

    def testPortfolioAnalysis(self):
        """Test PortfolioAnalysis"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
