# coding: utf-8

"""
    AM Portfolio API

    API for managing investment portfolios and market indices.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from am_portfolio_client.models.time_interval import TimeInterval

class TestTimeInterval(unittest.TestCase):
    """TimeInterval unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTimeInterval(self):
        """Test TimeInterval"""
        # inst = TimeInterval()

if __name__ == '__main__':
    unittest.main()
