# coding: utf-8

"""
    AM Portfolio API

    API for managing investment portfolios and market indices.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from am_portfolio_client.api.portfolio_api import PortfolioApi


class TestPortfolioApi(unittest.TestCase):
    """PortfolioApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PortfolioApi()

    def tearDown(self) -> None:
        pass

    def test_get_portfolio_analysis(self) -> None:
        """Test case for get_portfolio_analysis

        Get portfolio analysis
        """
        pass

    def test_get_portfolio_by_id(self) -> None:
        """Test case for get_portfolio_by_id

        Get portfolio by ID
        """
        pass

    def test_get_portfolios(self) -> None:
        """Test case for get_portfolios

        Get all portfolios for a user
        """
        pass


if __name__ == '__main__':
    unittest.main()
