# coding: utf-8

"""
    AM Portfolio API

    API for managing investment portfolios and market indices.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from am_portfolio_client.api.market_index_api import MarketIndexApi


class TestMarketIndexApi(unittest.TestCase):
    """MarketIndexApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MarketIndexApi()

    def tearDown(self) -> None:
        pass

    def test_get_all_market_indices(self) -> None:
        """Test case for get_all_market_indices

        Get all market indices
        """
        pass


if __name__ == '__main__':
    unittest.main()
