# coding: utf-8

"""
    AM Portfolio API

    API for managing investment portfolios and market indices.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from am_portfolio_client.models.portfolio_model_v1 import PortfolioModelV1

class TestPortfolioModelV1(unittest.TestCase):
    """PortfolioModelV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PortfolioModelV1:
        """Test PortfolioModelV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PortfolioModelV1`
        """
        model = PortfolioModelV1()
        if include_optional:
            return PortfolioModelV1(
                id = '',
                user_id = '',
                name = '',
                description = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return PortfolioModelV1(
        )
        """

    def testPortfolioModelV1(self):
        """Test PortfolioModelV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
