# coding: utf-8

"""
    AM Portfolio API

    API for managing investment portfolios and market indices.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class TimeInterval(str, Enum):
    """
    TimeInterval
    """

    """
    allowed enum values
    """
    ENUM_1D = '1D'
    ENUM_1W = '1W'
    ENUM_1M = '1M'
    ENUM_1Y = '1Y'
    ALL = 'ALL'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TimeInterval from a JSON string"""
        return cls(json.loads(json_str))


