apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "am-portfolio.fullname" . }}-config
  labels:
    {{- include "am-portfolio.labels" . | nindent 4 }}
data:
  ENVIRONMENT: {{ .Values.environment | quote }}
  LOG_LEVEL: "INFO"
