apiVersion: v1
kind: Service
metadata:
  name: {{ include "am-portfolio.fullname" . }}
  labels:
    {{- include "am-portfolio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8060
      protocol: TCP
      name: http
  selector:
    {{- include "am-portfolio.selectorLabels" . | nindent 4 }}
