/*
 * AM Portfolio API
 * API for managing investment portfolios and market indices.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.portfolio.api;

import com.am.portfolio.client.portfolio.invoker.ApiException;
import com.am.portfolio.client.portfolio.model.IndexIndices;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for MarketIndexApi
 */
@Disabled
public class MarketIndexApiTest {

    private final MarketIndexApi api = new MarketIndexApi();

    
    /**
     * Get all market indices
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllMarketIndicesTest() throws ApiException {
        String interval = null;
        String type = null;
        List<IndexIndices> response = 
        api.getAllMarketIndices(interval, type);
        
        // TODO: test validations
    }
    
}
