/*
 * AM Portfolio API
 * API for managing investment portfolios and market indices.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.portfolio.api;

import com.am.portfolio.client.portfolio.invoker.ApiException;
import com.am.portfolio.client.portfolio.model.PortfolioAnalysis;
import com.am.portfolio.client.portfolio.model.PortfolioModelV1;
import com.am.portfolio.client.portfolio.model.TimeInterval;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for PortfolioApi
 */
@Disabled
public class PortfolioApiTest {

    private final PortfolioApi api = new PortfolioApi();

    
    /**
     * Get portfolio analysis
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPortfolioAnalysisTest() throws ApiException {
        String portfolioId = null;
        String userId = null;
        TimeInterval interval = null;
        PortfolioAnalysis response = 
        api.getPortfolioAnalysis(portfolioId, userId, interval);
        
        // TODO: test validations
    }
    
    /**
     * Get portfolio by ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPortfolioByIdTest() throws ApiException {
        UUID portfolioId = null;
        PortfolioModelV1 response = 
        api.getPortfolioById(portfolioId);
        
        // TODO: test validations
    }
    
    /**
     * Get all portfolios for a user
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPortfoliosTest() throws ApiException {
        String userId = null;
        List<PortfolioModelV1> response = 
        api.getPortfolios(userId);
        
        // TODO: test validations
    }
    
}
