# coding: utf-8

# flake8: noqa

"""
    AM Portfolio API

    API for managing investment portfolios and market indices.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "MarketIndexApi",
    "PortfolioApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "IndexIndices",
    "PortfolioAnalysis",
    "PortfolioModelV1",
    "TimeInterval",
]

# import apis into sdk package
from am_portfolio_client.api.market_index_api import MarketIndexApi as MarketIndexApi
from am_portfolio_client.api.portfolio_api import PortfolioApi as PortfolioApi

# import ApiClient
from am_portfolio_client.api_response import ApiResponse as ApiResponse
from am_portfolio_client.api_client import ApiClient as ApiClient
from am_portfolio_client.configuration import Configuration as Configuration
from am_portfolio_client.exceptions import OpenApiException as OpenApiException
from am_portfolio_client.exceptions import ApiTypeError as ApiTypeError
from am_portfolio_client.exceptions import ApiValueError as ApiValueError
from am_portfolio_client.exceptions import ApiKeyError as ApiKeyError
from am_portfolio_client.exceptions import ApiAttributeError as ApiAttributeError
from am_portfolio_client.exceptions import ApiException as ApiException

# import models into sdk package
from am_portfolio_client.models.index_indices import IndexIndices as IndexIndices
from am_portfolio_client.models.portfolio_analysis import PortfolioAnalysis as PortfolioAnalysis
from am_portfolio_client.models.portfolio_model_v1 import PortfolioModelV1 as PortfolioModelV1
from am_portfolio_client.models.time_interval import TimeInterval as TimeInterval

