/*
 * AM Portfolio API
 * API for managing investment portfolios and market indices.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.portfolio.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.portfolio.client.portfolio.invoker.ApiClient;
/**
 * IndexIndices
 */
@JsonPropertyOrder({
  IndexIndices.JSON_PROPERTY_KEY,
  IndexIndices.JSON_PROPERTY_INDEX,
  IndexIndices.JSON_PROPERTY_INDEX_SYMBOL,
  IndexIndices.JSON_PROPERTY_TIMESTAMP
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-16T21:43:29.682309+05:30[Asia/Calcutta]", comments = "Generator version: 7.18.0")
public class IndexIndices {
  public static final String JSON_PROPERTY_KEY = "key";
  @javax.annotation.Nullable
  private String key;

  public static final String JSON_PROPERTY_INDEX = "index";
  @javax.annotation.Nullable
  private String index;

  public static final String JSON_PROPERTY_INDEX_SYMBOL = "indexSymbol";
  @javax.annotation.Nullable
  private String indexSymbol;

  public static final String JSON_PROPERTY_TIMESTAMP = "timestamp";
  @javax.annotation.Nullable
  private OffsetDateTime timestamp;

  public IndexIndices() { 
  }

  public IndexIndices key(@javax.annotation.Nullable String key) {
    this.key = key;
    return this;
  }

  /**
   * Get key
   * @return key
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getKey() {
    return key;
  }


  @JsonProperty(value = JSON_PROPERTY_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKey(@javax.annotation.Nullable String key) {
    this.key = key;
  }


  public IndexIndices index(@javax.annotation.Nullable String index) {
    this.index = index;
    return this;
  }

  /**
   * Get index
   * @return index
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INDEX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getIndex() {
    return index;
  }


  @JsonProperty(value = JSON_PROPERTY_INDEX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIndex(@javax.annotation.Nullable String index) {
    this.index = index;
  }


  public IndexIndices indexSymbol(@javax.annotation.Nullable String indexSymbol) {
    this.indexSymbol = indexSymbol;
    return this;
  }

  /**
   * Get indexSymbol
   * @return indexSymbol
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INDEX_SYMBOL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getIndexSymbol() {
    return indexSymbol;
  }


  @JsonProperty(value = JSON_PROPERTY_INDEX_SYMBOL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIndexSymbol(@javax.annotation.Nullable String indexSymbol) {
    this.indexSymbol = indexSymbol;
  }


  public IndexIndices timestamp(@javax.annotation.Nullable OffsetDateTime timestamp) {
    this.timestamp = timestamp;
    return this;
  }

  /**
   * Get timestamp
   * @return timestamp
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getTimestamp() {
    return timestamp;
  }


  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimestamp(@javax.annotation.Nullable OffsetDateTime timestamp) {
    this.timestamp = timestamp;
  }


  /**
   * Return true if this IndexIndices object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IndexIndices indexIndices = (IndexIndices) o;
    return Objects.equals(this.key, indexIndices.key) &&
        Objects.equals(this.index, indexIndices.index) &&
        Objects.equals(this.indexSymbol, indexIndices.indexSymbol) &&
        Objects.equals(this.timestamp, indexIndices.timestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(key, index, indexSymbol, timestamp);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IndexIndices {\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("    indexSymbol: ").append(toIndentedString(indexSymbol)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `key` to the URL query string
    if (getKey() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%skey%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getKey()))));
    }

    // add `index` to the URL query string
    if (getIndex() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sindex%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIndex()))));
    }

    // add `indexSymbol` to the URL query string
    if (getIndexSymbol() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sindexSymbol%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIndexSymbol()))));
    }

    // add `timestamp` to the URL query string
    if (getTimestamp() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stimestamp%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTimestamp()))));
    }

    return joiner.toString();
  }
}

