/*
 * AM Portfolio API
 * API for managing investment portfolios and market indices.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.portfolio.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.am.portfolio.client.portfolio.model.TimeInterval;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.portfolio.client.portfolio.invoker.ApiClient;
/**
 * PortfolioAnalysis
 */
@JsonPropertyOrder({
  PortfolioAnalysis.JSON_PROPERTY_PORTFOLIO_ID,
  PortfolioAnalysis.JSON_PROPERTY_LAST_UPDATED,
  PortfolioAnalysis.JSON_PROPERTY_CURRENT_INTERVAL
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-16T21:43:29.682309+05:30[Asia/Calcutta]", comments = "Generator version: 7.18.0")
public class PortfolioAnalysis {
  public static final String JSON_PROPERTY_PORTFOLIO_ID = "portfolioId";
  @javax.annotation.Nullable
  private String portfolioId;

  public static final String JSON_PROPERTY_LAST_UPDATED = "lastUpdated";
  @javax.annotation.Nullable
  private OffsetDateTime lastUpdated;

  public static final String JSON_PROPERTY_CURRENT_INTERVAL = "currentInterval";
  @javax.annotation.Nullable
  private TimeInterval currentInterval;

  public PortfolioAnalysis() { 
  }

  public PortfolioAnalysis portfolioId(@javax.annotation.Nullable String portfolioId) {
    this.portfolioId = portfolioId;
    return this;
  }

  /**
   * Get portfolioId
   * @return portfolioId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PORTFOLIO_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPortfolioId() {
    return portfolioId;
  }


  @JsonProperty(value = JSON_PROPERTY_PORTFOLIO_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPortfolioId(@javax.annotation.Nullable String portfolioId) {
    this.portfolioId = portfolioId;
  }


  public PortfolioAnalysis lastUpdated(@javax.annotation.Nullable OffsetDateTime lastUpdated) {
    this.lastUpdated = lastUpdated;
    return this;
  }

  /**
   * Get lastUpdated
   * @return lastUpdated
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LAST_UPDATED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getLastUpdated() {
    return lastUpdated;
  }


  @JsonProperty(value = JSON_PROPERTY_LAST_UPDATED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastUpdated(@javax.annotation.Nullable OffsetDateTime lastUpdated) {
    this.lastUpdated = lastUpdated;
  }


  public PortfolioAnalysis currentInterval(@javax.annotation.Nullable TimeInterval currentInterval) {
    this.currentInterval = currentInterval;
    return this;
  }

  /**
   * Get currentInterval
   * @return currentInterval
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CURRENT_INTERVAL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public TimeInterval getCurrentInterval() {
    return currentInterval;
  }


  @JsonProperty(value = JSON_PROPERTY_CURRENT_INTERVAL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCurrentInterval(@javax.annotation.Nullable TimeInterval currentInterval) {
    this.currentInterval = currentInterval;
  }


  /**
   * Return true if this PortfolioAnalysis object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PortfolioAnalysis portfolioAnalysis = (PortfolioAnalysis) o;
    return Objects.equals(this.portfolioId, portfolioAnalysis.portfolioId) &&
        Objects.equals(this.lastUpdated, portfolioAnalysis.lastUpdated) &&
        Objects.equals(this.currentInterval, portfolioAnalysis.currentInterval);
  }

  @Override
  public int hashCode() {
    return Objects.hash(portfolioId, lastUpdated, currentInterval);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PortfolioAnalysis {\n");
    sb.append("    portfolioId: ").append(toIndentedString(portfolioId)).append("\n");
    sb.append("    lastUpdated: ").append(toIndentedString(lastUpdated)).append("\n");
    sb.append("    currentInterval: ").append(toIndentedString(currentInterval)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `portfolioId` to the URL query string
    if (getPortfolioId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sportfolioId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPortfolioId()))));
    }

    // add `lastUpdated` to the URL query string
    if (getLastUpdated() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slastUpdated%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLastUpdated()))));
    }

    // add `currentInterval` to the URL query string
    if (getCurrentInterval() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scurrentInterval%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCurrentInterval()))));
    }

    return joiner.toString();
  }
}

