/*
 * AM Portfolio API
 * API for managing investment portfolios and market indices.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.am.portfolio.client.portfolio.api;

import com.am.portfolio.client.portfolio.invoker.ApiClient;
import com.am.portfolio.client.portfolio.invoker.ApiException;
import com.am.portfolio.client.portfolio.invoker.ApiResponse;
import com.am.portfolio.client.portfolio.invoker.Configuration;
import com.am.portfolio.client.portfolio.invoker.Pair;

import com.am.portfolio.client.portfolio.model.PortfolioAnalysis;
import com.am.portfolio.client.portfolio.model.PortfolioModelV1;
import com.am.portfolio.client.portfolio.model.TimeInterval;
import java.util.UUID;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-16T21:43:29.682309+05:30[Asia/Calcutta]", comments = "Generator version: 7.18.0")
public class PortfolioApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public PortfolioApi() {
    this(Configuration.getDefaultApiClient());
  }

  public PortfolioApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Get portfolio analysis
   * 
   * @param portfolioId  (required)
   * @param userId  (required)
   * @param interval  (optional)
   * @return PortfolioAnalysis
   * @throws ApiException if fails to make API call
   */
  public PortfolioAnalysis getPortfolioAnalysis(@javax.annotation.Nonnull String portfolioId, @javax.annotation.Nonnull String userId, @javax.annotation.Nullable TimeInterval interval) throws ApiException {
    return getPortfolioAnalysis(portfolioId, userId, interval, null);
  }

  /**
   * Get portfolio analysis
   * 
   * @param portfolioId  (required)
   * @param userId  (required)
   * @param interval  (optional)
   * @param headers Optional headers to include in the request
   * @return PortfolioAnalysis
   * @throws ApiException if fails to make API call
   */
  public PortfolioAnalysis getPortfolioAnalysis(@javax.annotation.Nonnull String portfolioId, @javax.annotation.Nonnull String userId, @javax.annotation.Nullable TimeInterval interval, Map<String, String> headers) throws ApiException {
    ApiResponse<PortfolioAnalysis> localVarResponse = getPortfolioAnalysisWithHttpInfo(portfolioId, userId, interval, headers);
    return localVarResponse.getData();
  }

  /**
   * Get portfolio analysis
   * 
   * @param portfolioId  (required)
   * @param userId  (required)
   * @param interval  (optional)
   * @return ApiResponse&lt;PortfolioAnalysis&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PortfolioAnalysis> getPortfolioAnalysisWithHttpInfo(@javax.annotation.Nonnull String portfolioId, @javax.annotation.Nonnull String userId, @javax.annotation.Nullable TimeInterval interval) throws ApiException {
    return getPortfolioAnalysisWithHttpInfo(portfolioId, userId, interval, null);
  }

  /**
   * Get portfolio analysis
   * 
   * @param portfolioId  (required)
   * @param userId  (required)
   * @param interval  (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;PortfolioAnalysis&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PortfolioAnalysis> getPortfolioAnalysisWithHttpInfo(@javax.annotation.Nonnull String portfolioId, @javax.annotation.Nonnull String userId, @javax.annotation.Nullable TimeInterval interval, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getPortfolioAnalysisRequestBuilder(portfolioId, userId, interval, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getPortfolioAnalysis", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<PortfolioAnalysis>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        PortfolioAnalysis responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<PortfolioAnalysis>() {});
        

        return new ApiResponse<PortfolioAnalysis>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getPortfolioAnalysisRequestBuilder(@javax.annotation.Nonnull String portfolioId, @javax.annotation.Nonnull String userId, @javax.annotation.Nullable TimeInterval interval, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'portfolioId' is set
    if (portfolioId == null) {
      throw new ApiException(400, "Missing the required parameter 'portfolioId' when calling getPortfolioAnalysis");
    }
    // verify the required parameter 'userId' is set
    if (userId == null) {
      throw new ApiException(400, "Missing the required parameter 'userId' when calling getPortfolioAnalysis");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/portfolios/{portfolioId}/analysis"
        .replace("{portfolioId}", ApiClient.urlEncode(portfolioId.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "userId";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("userId", userId));
    localVarQueryParameterBaseName = "interval";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("interval", interval));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get portfolio by ID
   * 
   * @param portfolioId  (required)
   * @return PortfolioModelV1
   * @throws ApiException if fails to make API call
   */
  public PortfolioModelV1 getPortfolioById(@javax.annotation.Nonnull UUID portfolioId) throws ApiException {
    return getPortfolioById(portfolioId, null);
  }

  /**
   * Get portfolio by ID
   * 
   * @param portfolioId  (required)
   * @param headers Optional headers to include in the request
   * @return PortfolioModelV1
   * @throws ApiException if fails to make API call
   */
  public PortfolioModelV1 getPortfolioById(@javax.annotation.Nonnull UUID portfolioId, Map<String, String> headers) throws ApiException {
    ApiResponse<PortfolioModelV1> localVarResponse = getPortfolioByIdWithHttpInfo(portfolioId, headers);
    return localVarResponse.getData();
  }

  /**
   * Get portfolio by ID
   * 
   * @param portfolioId  (required)
   * @return ApiResponse&lt;PortfolioModelV1&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PortfolioModelV1> getPortfolioByIdWithHttpInfo(@javax.annotation.Nonnull UUID portfolioId) throws ApiException {
    return getPortfolioByIdWithHttpInfo(portfolioId, null);
  }

  /**
   * Get portfolio by ID
   * 
   * @param portfolioId  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;PortfolioModelV1&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PortfolioModelV1> getPortfolioByIdWithHttpInfo(@javax.annotation.Nonnull UUID portfolioId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getPortfolioByIdRequestBuilder(portfolioId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getPortfolioById", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<PortfolioModelV1>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        PortfolioModelV1 responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<PortfolioModelV1>() {});
        

        return new ApiResponse<PortfolioModelV1>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getPortfolioByIdRequestBuilder(@javax.annotation.Nonnull UUID portfolioId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'portfolioId' is set
    if (portfolioId == null) {
      throw new ApiException(400, "Missing the required parameter 'portfolioId' when calling getPortfolioById");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/portfolios/{portfolioId}"
        .replace("{portfolioId}", ApiClient.urlEncode(portfolioId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get all portfolios for a user
   * 
   * @param userId  (required)
   * @return List&lt;PortfolioModelV1&gt;
   * @throws ApiException if fails to make API call
   */
  public List<PortfolioModelV1> getPortfolios(@javax.annotation.Nonnull String userId) throws ApiException {
    return getPortfolios(userId, null);
  }

  /**
   * Get all portfolios for a user
   * 
   * @param userId  (required)
   * @param headers Optional headers to include in the request
   * @return List&lt;PortfolioModelV1&gt;
   * @throws ApiException if fails to make API call
   */
  public List<PortfolioModelV1> getPortfolios(@javax.annotation.Nonnull String userId, Map<String, String> headers) throws ApiException {
    ApiResponse<List<PortfolioModelV1>> localVarResponse = getPortfoliosWithHttpInfo(userId, headers);
    return localVarResponse.getData();
  }

  /**
   * Get all portfolios for a user
   * 
   * @param userId  (required)
   * @return ApiResponse&lt;List&lt;PortfolioModelV1&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<PortfolioModelV1>> getPortfoliosWithHttpInfo(@javax.annotation.Nonnull String userId) throws ApiException {
    return getPortfoliosWithHttpInfo(userId, null);
  }

  /**
   * Get all portfolios for a user
   * 
   * @param userId  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;List&lt;PortfolioModelV1&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<PortfolioModelV1>> getPortfoliosWithHttpInfo(@javax.annotation.Nonnull String userId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getPortfoliosRequestBuilder(userId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getPortfolios", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<List<PortfolioModelV1>>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        List<PortfolioModelV1> responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<List<PortfolioModelV1>>() {});
        

        return new ApiResponse<List<PortfolioModelV1>>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getPortfoliosRequestBuilder(@javax.annotation.Nonnull String userId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'userId' is set
    if (userId == null) {
      throw new ApiException(400, "Missing the required parameter 'userId' when calling getPortfolios");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/portfolios";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "userId";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("userId", userId));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
