# Pre-production Environment Configuration
environment: prod

# Application Configuration
config:
  marketData:
    maxRetries: 3
    retryDelayMs: 1000
    threadPoolSize: 5
    threadQueueCapacity: 10
    maxAgeMinutes: 15

# Service Configuration
service:
  type: ClusterIP
  port: 8060

# Ingress Configuration
ingress:
  enabled: true
  ipAddress: 20.59.109.241

# Resource Configuration
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

postgresql:
  enabled: true
  fullname: host.docker.internal
  auth:
    database: portfolio
    username: postgres
    password: ""
  primary:
    service:
      port: 5452


# Vault Configuration
vault:
  enabled: true
  secretPaths:
    infra: "kv/data/prod/infra"
    mongo: "kv/data/prod/apps/portfolio/database/mongo"
    redis: "kv/data/prod/apps/portfolio/database/redis"
    postgres: "kv/data/prod/apps/portfolio/database/postgres"
    influx: "kv/data/prod/apps/portfolio/database/influxdb"
    kafka: "kv/data/prod/apps/portfolio/kafka"
    upstox: "kv/data/prod/apps/portfolio/api/upstock"
    zerodha: "kv/data/prod/apps/portfolio/api/zerodha"
    app: "kv/data/prod/apps/portfolio"


# Monitoring Configuration
monitoring:
  enabled: true
  prometheus:
    scrape: true
    port: "8060"
    path: "/actuator/prometheus"

image:
  repository: ghcr.io/am-portfolio/am-portfolio
  tag: prod
  pullPolicy: IfNotPresent

deployment:
  version: prod
