/*
 * AM Portfolio API
 * API for managing investment portfolios and market indices.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.portfolio.model;

import com.am.portfolio.client.portfolio.model.TimeInterval;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PortfolioAnalysis
 */
class PortfolioAnalysisTest {
    private final PortfolioAnalysis model = new PortfolioAnalysis();

    /**
     * Model tests for PortfolioAnalysis
     */
    @Test
    void testPortfolioAnalysis() {
        // TODO: test PortfolioAnalysis
    }

    /**
     * Test the property 'portfolioId'
     */
    @Test
    void portfolioIdTest() {
        // TODO: test portfolioId
    }

    /**
     * Test the property 'lastUpdated'
     */
    @Test
    void lastUpdatedTest() {
        // TODO: test lastUpdated
    }

    /**
     * Test the property 'currentInterval'
     */
    @Test
    void currentIntervalTest() {
        // TODO: test currentInterval
    }

}
